<?php

namespace TouchQue\Tests;

use PHPUnit\Framework\TestCase;
use TouchQue\Config;
use TouchQue\Http\HttpClient;
use TouchQue\Resources\Webhook;

/**
 * Cross-language SDK contract fixtures, generated by the backend from its own
 * utils/canonicalSignature.js + utils/webhookCanonical.js. Asserted here and in
 * the node/go/python suites so every SDK signs and canonicalises identically to
 * the server (would have caught the 2026-08 webhook + GET-query regressions).
 */
class VectorsTest extends TestCase
{
    private static function fixture(string $name): array
    {
        return json_decode(file_get_contents(__DIR__ . '/../fixtures/' . $name), true);
    }

    private function callPrivate(object $obj, string $method, array $args)
    {
        $ref = new \ReflectionMethod($obj, $method);
        $ref->setAccessible(true);
        return $ref->invokeArgs($obj, $args);
    }

    public function testSignatureVectors(): void
    {
        $fx = self::fixture('signature-vectors.json');
        $this->assertNotEmpty($fx['vectors']);
        $client = new HttpClient(new Config('tq_x', $fx['secret']));

        foreach ($fx['vectors'] as $v) {
            $actual = $this->callPrivate($client, 'signRequest', [
                $v['method'], $v['signed_path'], $v['body'], $v['timestamp'], $v['nonce'],
            ]);
            $this->assertSame($v['expected_signature'], $actual, $v['description']);
        }
    }

    public function testWebhookVectors(): void
    {
        $fx = self::fixture('webhook-vectors.json');
        $this->assertNotEmpty($fx['vectors']);
        $webhook = new Webhook(new Config('tq_x', $fx['secret']));

        foreach ($fx['vectors'] as $v) {
            // Decode the raw delivered body exactly as verify() does (objects,
            // not assoc) so an empty {} stays an object.
            $obj = json_decode($v['delivered_body']);
            $canonical = $this->callPrivate($webhook, 'canonicalize', [$obj]);
            $this->assertSame($v['expected_canonical'], $canonical, $v['description']);

            // Fixtures carry a fixed past timestamp -> disable the replay check.
            $result = $webhook->verify($v['delivered_body'], null, 0);
            $this->assertSame($v['payload']['requestId'], $result['requestId'], $v['description']);
        }
    }
}
